### ISSUE TITLE
The letter size does not change and no cover image

### ISSUE THREAD

**Issue by ambrits** [GuardKenzie/miniplayer#19]
Hi!

In the Config file, if I set any size, nothing changes. A 5 "monitors are unreadable small letters.
The other problem is that the covers do not appear.
My Music folder:
/ MNT / Music / Blues
/ MNT / Music / Rock
/ MNT / Music / Jazz

The setting is:
[art]
Image_method = ueberzug
Music_directory = / MNT / Music
http_base_url = http://192.168.1.2:88
http_cover_filenames = cover.jpg

Can you help me?
![IMG_6162](https://user-images.githubusercontent.com/2150083/148371688-9206714f-4d65-4b32-a3e5-d80aca2a6707.jpg)

**Comment by GuardKenzie** [comment]
For your first issue, what do you mean exactly? The font size can only be determined by your terminal, not by any cli app you use if that's what you are talking about. The font width and height settings are so that the album art can be centered properly.

As for your second issue: Are you using an X11 based window manager and if so, which terminal emulator are you running?

**Comment by ambrits** [comment]
Then if I understand you good, I have to change the size iof console font to be readable?

I don't use Windows Manager

**Comment by GuardKenzie** [comment]
Yes, the terminal emulator (or in your case, the virtual terminal) is responsible for handling colours, fonts, font sizes etc. I am not sure if you can change these attributes in the virtual terminal but it might be worth a google.

The virtual terminal has no graphical capabilities so there is no way for Überzug and Pixcat to display any album art. You will need to use a window manager for the album art to function.

**Comment by ambrits** [comment]
Thank you!
